models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

db = SQLAlchemy()


class User(UserMixin, db.Model):
    """ User model """

    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(25), unique=True, nullable=False)
    password = db.Column(db.String(), nullable=False)

models/User.py
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


class User(UserMixin, db.Model):
    """User model"""

    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(25), unique=True, nullable=False)
    password = db.Column(db.String(), nullable=False)

app.py
import os
import time

from flask import Flask, flash, redirect, render_template, url_for
from flask_login import LoginManager, current_user, login_user, logout_user
from flask_socketio import SocketIO, join_room, leave_room, send
from passlib.hash import bcrypt_sha256

from models.User import SQLAlchemy, User
from routes.Chat import construct_chat_blueprint
from routes.Home import construct_home_blueprint
from routes.Login import loginRoute
from routes.Logout import logoutRoute

# from utils.wtform_fields import RegistrationForm

# config flask app
app = Flask(__name__)
app.secret_key = os.environ["SECRET_KEY"]

# config postgres db
app.config["SQLALCHEMY_DATABASE_URI"] = os.environ["DB_URL"]
# app.config["SQLALCHEMY_DATABASE_URI"] = os.environ["DB_URL"].replace( "postgres", "postgresql")
db = SQLAlchemy(app)

# config flask-socketio
socketio = SocketIO(app)

# config flask-login for session management
login_manager = LoginManager(app)
login_manager.init_app(app)


# room list
ROOMS = ["lounge", "news", "games", "coding"]


@app.errorhandler(404)
def page_not_found(_):
    return render_template("404.html"), 404


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).first()


# logout route
app.register_blueprint(logoutRoute, url_prefix="")

# login route
app.register_blueprint(loginRoute, url_prefix="")

# chat route
app.register_blueprint(construct_chat_blueprint(ROOMS), url_prefix="")

# home route
app.register_blueprint(construct_home_blueprint(db), url_prefix="")


# message event
@socketio.on("message")
def message(data):
    msg = data["msg"]
    username = data["username"]
    room = data["room"]
    time_stamp = time.strftime("%b-%d %I:%M%p", time.localtime())
    send({"username": username, "msg": msg, "time_stamp": time_stamp}, room=room)


# user joined the room
@socketio.on("join")
def on_join(data):
    username = data["username"]
    room = data["room"]
    join_room(room)
    send({"msg": username + " has joined the " + room + " room."}, room=room)


# user left the room
@socketio.on("leave")
def on_leave(data):
    username = data["username"]
    room = data["room"]
    leave_room(room)
    send({"msg": username + " has left the room"}, room=room)


if __name__ == "__main__":
    if os.environ["LOCAL"]:
        # if running locally
        socketio.run(app, debug=True)
    else:
        # if running on heroku
        app.run()

routes/Chat.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user

def construct_chat_blueprint(ROOMS):
    chatRoute = Blueprint(
        "chat", __name__, static_folder="static", template_folder="templates"
    )

    # chat route
    @chatRoute.route("/chat", methods=["GET", "POST"])
    def chat():
        if not current_user.is_authenticated:
            flash("Please login", "danger")
            return redirect(url_for("login.login"))
        return render_template("chat.html", username=current_user.username, rooms=ROOMS)

    return chatRoute

routes/Home.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user
from passlib.hash import bcrypt_sha256

from utils.wtform_fields import RegistrationForm, User


def construct_home_blueprint(db):
    homeRoute = Blueprint(
        "/", __name__, static_folder="static", template_folder="templates"
    )

    @homeRoute.route("/home", methods=["GET", "POST"])
    @homeRoute.route("/", methods=["GET", "POST"])
    def home():
        # redirect user to chat page if already login
        if current_user.is_authenticated:
            return redirect(url_for("chat.chat"))
        reg_form = RegistrationForm()

        # if POST is used and form is validated
        if reg_form.validate_on_submit():
            username = reg_form.username.data
            password = reg_form.password.data
            hashed_password = bcrypt_sha256.hash(password)
            user = User(username=username, password=hashed_password)
            db.session.add(user)
            db.session.commit()

            flash("Registered Successfully. Please Login", "success")
            return redirect(url_for("login.login"))

        return render_template("index.html", form=reg_form)

    return homeRoute

routes/Login.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import login_user

from models.User import User
from utils.wtform_fields import LoginForm

loginRoute = Blueprint(
    "login", __name__, static_folder="static", template_folder="templates"
)

# login route
@loginRoute.route("/login", methods=["GET", "POST"])
def login():
    login_form = LoginForm()

    # if POST is used and login successful
    if login_form.validate_on_submit():
        user_object = User.query.filter_by(username=login_form.username.data).first()
        login_user(user_object)
        return redirect(url_for("chat.chat"))

    return render_template("login.html", form=login_form)

routes/Logout.py
from flask import Blueprint, flash, redirect, url_for
from flask_login import logout_user

logoutRoute = Blueprint(
    "logout", __name__, static_folder="static", template_folder="templates"
)

# logout route
@logoutRoute.route("/logout", methods=["GET"])
def logout():
    logout_user()
    flash("Logged out successfully", "success")
    return redirect(url_for("login.login"))

templates/chat.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Chat Away - RChat</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Custom css for chat pages -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/chat_style.css') }}">
</head>

<body>
    <!-- Flash error messages -->
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <p class=formError>{{ messages[0] }}</p>
    {% endif %}
    {% endwith %}

    <div class="wrapper">

        <!-- Nav bar start -->
        <nav class="navbar navbar-expand-sm navbar-light fixed-top" style="background-color: #66a1ee">

            <div class="container-fluid">
                <div id="show-sidebar-button" class="cursor-pointer">
                    <i class="fas fa-plus-circle "></i>
                    <span>Rooms</span>
                </div>

                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a id="logout-btn" class="nav-link" href="{{ url_for('logout.logout') }}"><spanhtml
                                    style="color: #335177">Logout</span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Nav bar end -->

        <!-- Main section start -->
        <div id="main-section">

            <!-- Sidebar start -->
            <nav id="sidebar">
                <h4>Rooms</h4>
                {% for room in rooms %}
                <p id="{{ room|title }}" class="select-room cursor-pointer">{{ room|title }}</p>
                {% endfor %}
            </nav>
            <!-- Sidebar end -->

            <!-- Rightside pannel start -->
            <div id="rightside-pannel">

                <!-- Display message start-->
                <div id="display-message-section">
                </div>
                <!-- Display message end -->

                <!-- Type message start -->
                <div id="input-area" class="input-group mb-3">
                    <input type="text" id="user_message" class="form-control" placeholder="Type here..."
                        aria-label="Type a message" aria-describedby="basic-addon2" autocomplete="off">
                    <div class="input-group-append">
                        <button id="send_message" class="btn btn-warning" type="button">SEND <i
                                class="fas fa-paper-plane"></i></button>
                    </div>
                </div>
                <!-- Type message end -->
            </div>
            <!-- Rightside pannel end -->
        </div>
        <!-- Main section end -->
    </div>
    <!-- Wrapper end -->

    <!-- Custom chat JS -->
    <script src="{{ url_for('static', filename='scripts/chat_page.js') }}"></script>

    <!-- Socket.IO -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"
        integrity="sha512-q/dWJ3kcmjBLU4Qc47E4A9kTB4m3wuTY7vkFJDTZKjTs8jhyGQnaUrxa0Ytd0ssMZhbNua9hE+E7Qv1j+DyZwA=="
        crossorigin="anonymous"></script>

    <!-- Get username -->
    <script type="text/javascript" charset="utf-8">
        var socket = io();
        // username;
        const username = `{{ username }}`;
    </script>

    <!-- Custom SocketIO JS -->
    <script src="{{ url_for('static', filename='scripts/socketio.js') }}"></script>

    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
        integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ"
        crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"
        integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY"
        crossorigin="anonymous"></script>

</body>

</html>

templates/field-macro.html
{# Render form fields #}
{% macro displayField(field, fieldName) %}
    <div class="form-group">
        {{ field(class_='form-control', placeholder=fieldName, **kwargs) }}
        <!-- Error messages -->
        <ul class="formError">
            {% for error in field.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
{% endmacro %}

templates/form_helper.html
{% macro displayField(field, fieldName) %}

<div>
    {{ field(class_='form-control', placeholder=fieldName, **kwargs) }}

    <!-- errors -->
    <ul>
        {% for error in field.errors %}
        <li> {{ error }}</li 
        {% endfor %} 
    </ul>
</div>

{% endmacro %}

templates/index.html
{% from 'field-macro.html' import displayField %}
{% extends "prelogin-layout.html" %}

{% block title %}Register {% endblock title%}

{% block content %}
<div style="padding: 40px;">
    <h2>Get started!</h2>
    <p>First time here? Register to start using Rchat</p>

    <form action="{{ url_for('/.home') }}" , method="POST">
        {{ displayField(form.username, 'Username', autocomplete="off", autofocus=true) }}
        {{ displayField(form.password, 'Password') }}
        {{ displayField(form.cnfrm_password, 'Retype Password') }}
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-warning">
        </div>
        {{ form.csrf_token }}
    </form>

    <hr>

    <p>Already registered? <a href={{url_for('login.login')}}>Login here</a>.</p>
</div>
{% endblock %}

templates/login.html
{% from 'field-macro.html' import displayField %}
{% extends "prelogin-layout.html" %}

{% block title %}Login {% endblock %}

{% block content %}
<div style="padding: 40px;">
    <h2>Login now!</h2>
    <p>Enter you username/password to start RChat</p>

    <form action="{{ url_for('login.login') }}" , method="POST">
        {{ displayField(form.username, 'Username', autocomplete="off", autofocus=true) }}
        {{ displayField(form.password, 'Password') }}
        <div class="form-group">
            <input type="submit" value="Login" class="btn btn-warning">
        </div>
        {{ form.csrf_token }}
    </form>
    <hr>

    <p>Have not registered? <a href={{url_for('/.home')}}>Register here</a>.</p>
</div>
{% endblock %}

templates/prelogin-layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title %}{% endblock %} - RChat</title>

        <!-- Bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <!-- Custom css for prelogin pages -->
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/main_style.css') }}">
    </head>

    <body>
        <!-- Main section start -->
        <div class="main-section">

            <div class="jumbotron">
              <h1 class="display-4">RChat</h1>
              <p class="lead">Chat rooms are back! </p>
              <p class="lead"> <a href="https://github.com/dhruvSHA256/cshat-chat-app" target="_blank">  View source on Github </a> </p>
            </div>

            <!-- Righthand side start -->
            <div id="righthand-side">

                <!-- Flash error messages start -->
                {% with messages = get_flashed_messages(with_categories=true) %}
                    <!-- The messages, if any, are returned as a list. And not all redenring of the pages will have a message. So we put a condition to check whether the messages list is empty -->
                    {% if messages %}
                        <!-- We will set the class form our custom css file we had created earlier. And we want to see the first item in the list. -->
                        <div class="alert alert-{{ messages[0][0] }} " role="alert">
                            {{ messages[0][1] }}
                        </div>
                        <hr>
                    {% endif %}
                {% endwith %}
                <!-- Flask error messages end -->

                {% block content%}
                {% endblock %}

            </div>
            <!-- Righthand side end -->
        </div>
        <!-- Main section end -->

    </body>
</html>